### ISSUE TITLE
German translation issues

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2318]
[Some terms have already been treated in #2295, but I thought a separate issue makes more sense to distinguish this from layout issues.]
The tabular summary of nodes still contains English words
* The "quantors" "all", "mostly" (-> "alles", "meist")
* names of node levels ("area", "crag", "sector")

**Comment by scd** [comment]
Thanks @MelwinQ . Actually can I ask you to tag translations issues with 'Feature: Translations' so when I get around to it the issues are easy to find.

**Comment by birgander2** [comment]
Not everything is easy to translate into good German. Here are some ideas:

- "all" -> "ausschließlich" or "nur", but probably the best German would be just using an empty string
- "mostly" -> "vor allem" / "v.a." 
- "area" -> "Gegend"
- "crag" -> "Klettergebiet". Hard to translate, German is quite specific here and there are other possible translations depending on the crag characteristics, e.g. Felsen, Massiv, Klettergarten, ... 
- "sector" -> "Sektor"

**Comment by brendanheywood** [comment]
>  depending on the crag characteristics, e.g. Felsen, Massiv, Klettergarten

I'm curious about this. Would these actually be candidates for new nose types? Can you describe each and what they'd mean?

**Comment by MelwinQ** [comment]
While "crag" has no direct equivalent in German, I don't think new node types are required.
As I understand http://www.thecrag.com/article/AreaTypes,  "crag" is somehow defined by its surroundings: A solitary cliff with nothing else nearby could be a crag, while it is possibly only a "cliff" or "sector" when set among other structure of the same quality, right?
Can we consider "crag" a name I would use to tell someone colloquially where I am gonna climb on the weekend? If that is the case I'd suggest
"Kletterziel" (very general)
"Kletterspot" (poor anglicism)
or
"Felsgruppe" (preferred)
There does not seem to be a shortage of German speakers in this forum, so probably anyone  comes up with a better idea.

**Comment by birgander2** [comment]
No, no new node types, that would be an overkill. I tend to "Klettergebiet" or "Kletterspot" as most appropriate translations for crag. However, probably the best idea is to  just leave it to "crag". I think almost everybody will understand, and this is thecrag, or not?

**Comment by scd** [comment]
We use the word `crag` colloquially as a climbing area.

**Comment by MelwinQ** [comment]
I would not recommend "crag". I have never heard this being used in German climbers' speech.
I am afraid that this word is even unfamiliar to Germans with average English skills. Also, I find anglicisms in German not desirable, if there are alternatives. 
Even though this being "thecrag", this label is unfortunate for German ears, as most will likely hear and speak it as "the crack" (or rather "ze crack"; at least this also related to climbing). So thecrack.de /.com will surely draw a lot of hearsay visitors. An additional, more unique German domain alias directing to thecrag.com would help, if one wanted to avoid that. (e.g. kletterdatenbank.de - not half as sexy, but unequivocal and still vacant). Not sure though, how much you want to push on that "German issue", just telling you my impressions.

**Comment by birgander2** [comment]
No worries, but please also not "Kletterziel" or "Felsgruppe". "Climbing area" would translate to "Klettergebiet". It seems like someone has to make a decision...

**Comment by UFU608** [comment]
We actually use Klettergebiet in the translated version for that already, e.g. Lieblingsklettergebiet = Favourite Crag and propose to stick with that. I'll put up a list of translated area types soon. Be aware that not all of it is on Prod yet...

**Comment by MelwinQ** [comment]
* During logging an ascent, the personal star-rating is still in English.
* If a node has no information yet, the button "Add Gebiet information" appears. "Gebietsinformationen hinzufügen" would be better
* If a node has no route yet, is says "Dieses klettergebiet hat noch keine Untergebiete oder Routen!

Solltest du dieses klettergebiet kennen, füge bitte deine Informationen hinzu. Danke!" Please correct to "Klettergebiet"

**Comment by MelwinQ** [comment]
* with photos, the text says "taken vor 7 Jahren" or "uploaded vor 3 Wochen"

**Comment by UFU608** [comment]
Thanks for all the useful input - we are still translating and putting new sections on-line one after the other so you will see these issues dissapear over time. But please keep informing us and suggesting terms or any misspellings you might identify - more eyes are always better ;-)

**Comment by Drazhar** [comment]
Hey, there is a typo at "aktualisiert":
![image](https://cloud.githubusercontent.com/assets/3040689/18077583/f28eed7c-6e86-11e6-80d5-1446d70a1632.png)

**Comment by Drazhar** [comment]
And does "künstliches Gebiet" make sense? Typically you would say "Kletterhalle" oder "Boulderhalle", so I would just say "Halle". The only thing where this would be wrong is for artificial climbing walls outdoor, which is quite uncommon.

In English it is also just "Gym" and not "artificial area", which sounds strange.

**Comment by UFU608** [comment]
Thanks for the comments, the Typo and the "artificial area" are corrected on Dev.

**Comment by nicHoch** [comment]
theCrag distinguishes between "gym" and "artificial area"

a gym is clearly a gym an artificial area is something like this:

https://www.thecrag.com/climbing/switzerland/mittelland/aargau/area/286639557

so the german translation should reflect that as well.

Am 30.08.2016 um 10:27 schrieb UFU608:

**Comment by UFU608** [comment]
We took care of that in the translation  - it is consistent

**Comment by MelwinQ** [comment]
when bulk editing:
"Seite 6 von 111. Du hast von 111 Einträgen 45 geprüft und 41 aktualisiert Aktualisierungen werden erst aktiv, wenn [...]"
missing "." after "aktualisiert"

**Comment by MelwinQ** [comment]
Very first comment of this issue still applies, e.g.
https://www.thecrag.com/climbing/germany/katzensteingebiet

**Comment by MelwinQ** [comment]
New section contains
"Updated 7 areas and 70 routes - full details."
German:
"aktualisierte 7 Gebiete und 70 Routen - Details."

**Comment by MelwinQ** [comment]
List of check boxes appearing after choosing "bulk edit" is still completely in English.

**Comment by MelwinQ** [comment]
In Bulk-editing menu:
"Die oben eingefügten Beschreibungen werden theCrag Kletterplattform zugeschrieben.."
should rather be
"Die oben eingefügten Beschreibungen werden bei theCrag Kletterplattform aufgenommen."

**Comment by MelwinQ** [comment]
"back to top" in the top right of the standard view should be
"zum Anfang"

**Comment by MelwinQ** [comment]
Dropdown below "Logbook" is 
---
Katzensteinnadel
Ascents
Your ascents
Friends ascents
Your ascents
Alle Begehungen von dir
Trad CPR
Sport CPR
Boulder CPR
Gym Sport CPR
Gym Boulder CPR
-------
should be
---------
Katzensteinnadel
Begehungen
Deine Beg. 
Beg. von Freunden
Deine Beg. 
Alle Begehungen von dir
Trad. CPR
Sport CPR
Boulder CPR
Halle Sport CPR
Halle Boulder CPR

**Comment by MelwinQ** [comment]
As mentioned in #2394, climbing style "trad" has no direct analogon in German.
It should be "traditionell", not "traditional" in the small labels next to a route.

**Comment by MelwinQ** [comment]
Dropdown "Hilfe" (Help) is mainly in English still.

**Comment by MelwinQ** [comment]
when logging an ascent, the dropdown "Partner" should be translated like this:
You -> Du
you follow -> Du folgst
you have mentioned -> von Dir erwähnt
local karma -> Lokale Karma-Helden

**Comment by MelwinQ** [comment]
Detailed view of a route is still completely in English, e.g.
https://www.thecrag.com/climbing/germany/katzensteingebiet/route/546832605

**Comment by rouletout** [comment]
- fixed traditional
- zugeschrieben was left as is as it is about copyright, sounds funny but is correct in German
- Help menu is German now
- Halle Sport CPR etc. fixed

Open are
- route detail page not yet translated
- Log Ascent Dropdown Partner not translated yet
