### ISSUE TITLE
Improvements to CPR charts

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2665]
Looks good guys, few minor bugs that I've found at this stage - may fix themselves over the next few days, but I figured I'd record them here

- Draw order is different for CPR curves. Seems pinkpoint curve draws over the OS one. 
![image](https://cloud.githubusercontent.com/assets/22091505/24341898/db705f78-1308-11e7-9cee-6fd7f790add2.png)

- Is there some way to set the max on the vertical scale? I couldn't find it in the few minutes I spent... means most of the curves are off the top, it'd be nice to be able to choose to see them at least, even if it defaults to a view that is limited to your actual ticks... Either that or I'll log a few attempts on ridiculous problems

**Comment by scd** [comment]
The scale should pick itself correctly. I think this will fix itself in the next couple of hours.

**Comment by birgander2** [comment]
It seems not to be possible anymore to exclude artificial ascents. The profile page lists only my natural ascents, but I think the CPR still includes the artificial ones. In fact, I really would like to switch between both, this was possible before (though not solved well).

I also encounter the problem that most of the curves are off the top. But let's wait for tomorrow.

**Comment by scd** [comment]
CPR should not include artificial ascents. There may of course be a bug if you can point out an example.

The artificial ascents selection field has been moved to the general profile settings page

**Comment by Drazhar** [comment]
Well mine look also quite off. First there is the problem with the scale which should fix itself in some time I think?
And then there is the value of the CPR. I don't think it should be above 7c for sport and above 8A for bouldering in my case, if you look at the grades I climbed.

![unbenannt-1](https://cloud.githubusercontent.com/assets/3040689/24349772/564ccfca-12e0-11e7-88a7-8c6de78ada01.jpg)

**Comment by birgander2** [comment]
* "click on that link and which should take you to the ascents search page that was used to generate the timeline" - this at least shows lots of artificial ascents for me. In any case, CPR either include artifical climbs, or it is impossible to visualise only artifical climbs.
* the scale looks better now,. indeed it took some time. Maybe add the current performance number at a more prominent position at the top?
* the older christmas trees above show V-grades now for me. I never climbed a V boulder and it is not possible anymore to configure this. Anyway, I think they are not really needed anymore!?
* I think it would be good to be able to configure the intervals used for the plots. If you don't climb so regularly, the sparse bars don't look good and yearly intervals would be better.

Overall, looks cool. Direct links to crag & area rankings are missing, though!

**Comment by scd** [comment]
> And then there is the value of the CPR. I don't think it should be above 7c for sport and above 8A for bouldering in my case, if you look at the grades I climbed.

@Drazhar has it fixed itself? Also I just want to make sure I understand which aspect you are referring to. Are you referring to the black line? If so, it is meant to be a climber performance line taking into account multiple ascents and different tick types. We really do want feedback on this as we see our configuration as version 1.

> "click on that link and which should take you to the ascents search page that was used to generate the timeline" - this at least shows lots of artificial ascents for me. In any case, CPR either include artifical climbs, or it is impossible to visualise only artifical climbs

 - [ ] @birgander2 that is a bug in the list of ascents. We have missed a setting in the url, but it does not effect the CPR. Compare

https://www.thecrag.com/ascents/in-setting/natural/with-route-gear-style/sport/by/anderlnought/?sortby=rating,desc

and 

https://www.thecrag.com/ascents/with-route-gear-style/sport/by/anderlnought/?sortby=rating,desc

> the scale looks better now, indeed it took some time. Maybe add the current performance number at a more prominent position at the top?

At the moment we are not pushing this performance number too hard because it is a totally new concept and we are scared it might be two much too soon. I am interested to know how you feel about having a number and whether it is worth branding more. Of course different people will have very different opinions here.

> the older christmas trees above show V-grades now for me. I never climbed a V boulder and it is not possible anymore to configure this. Anyway, I think they are not really needed anymore!?

We will revamp the whole profile page and the christmas trees will be redone. This is a regression issue on our part, sorry. As part of the cpr release we upgraded our capabilities with handing displays of aggregate data. It is pretty awesome, but will take a while to port everything across.

> I think it would be good to be able to configure the intervals used for the plots. If you don't climb so regularly, the sparse bars don't look good and yearly intervals would be better.

It is there under the hood, but we are opting for auto configure right now. If you want to play look at:

https://www.thecrag.com/ascents/aggregate/graph-sport-cpr/with-route-gear-style/sport/by/anderlnought/?period=year

year,quarter,month,fortnight,week,day

**Comment by scd** [comment]
FYI, I fixed the gym ascents issue.

**Comment by DaneEvans** [comment]
A few more thoughts:

- The CPR line goes to the middle of the grade bar, while a send of a route at that grade goes to the top of the grade bar. Hence if you only logged actual sends, the CPR line is always slightly below what you were actually doing. 

- The default graphs don't show the current partial period, it feels a little odd to look at it and realise the data on the right is now 3 months old.

**Comment by scd** [comment]
> The default graphs don't show the current partial period, it feels a little odd to look at it and realise the data on the right is now 3 months old.

 - [ ] Missing the last couple of months of ticks on the graph looks like a bug. 

> The CPR line goes to the middle of the grade bar, while a send of a route at that grade goes to the top of the grade bar. Hence if you only logged actual sends, the CPR line is always slightly below what you were actually doing.

The behavior is correct and part of the settings. Firstly a grade is a range, so the base CPR you get is mathematically based on the grade range and ends up being a little above half way between. In otherwords it differentiates between 5.10 and 5.10d. Secondly if you do multiple ascents then the CPR is commutative. So multiple ascents at the same grade increase your CPR. (Approximately 5 ascents at one grade will give you the higher grade's CPR).

Finally we have a setting which adjusts the final result on the basis that it takes about 3 ascents at a grade before you can really say you are solid at the grade.

This is all part of the configuration and what we want to get feedback from the climbing community. It is also mentioned in detail in the cpr article:

https://www.thecrag.com/article/CPR

**Comment by birgander2** [comment]
> I am interested to know how you feel about having a number and whether it is worth branding more. Of      course different people will have very different opinions here.

I think it's a good idea, people like this nowadays. A nice feature would be a button at every area / crag, generating a ranking for this area. Ok, that's maybe a bit 8a.nu-ish, but look at the success they have with their crappy page.

> FYI, I fixed the gym ascents issue.

Thanks! Still missing is the possibility to generate a gym CPR graph. Switching in my profile seems not to be enough; [this url trick also doesn't work](https://www.thecrag.com/ascents/with-route-gear-style/sport/in-setting/artificial/by/anderlnought/?sortby=rating,desc)

Some more ideas:
* Make interval size (months, years) configurable and also the number of years to display.
* Display (maximum? mean?) CPR values for each year. Probably a bit tricky to realise without making the graph too complex. 8a.nu does this quite nicely in my opinion.

**Comment by Drazhar** [comment]
My problem fixed itself. Now the values seem reasonable :)

**Comment by scd** [comment]
> Thanks! Still missing is the possibility to generate a gym CPR graph. Switching in my profile seems not to be enough; this

Gym CPR still on our todo list. All the theory in the outdoor CPR assumes consistent grading, which is close enough for outdoor, but not valid for indoor climbing. We have still got some understanding to get for the gym stuff here. 

> Still missing is the possibility to generate a gym CPR graph

It's there. Go to the Climbers tab at an area.

**Comment by birgander2** [comment]
> All the theory in the outdoor CPR assumes consistent grading, which is close enough for outdoor, but not valid for indoor climbing. 

Maybe. But this seems impossible to solve!? And if, it is up to the gym owners. Anyway, this is probably mostly good for documenting your own progress, so why not leave it as good as it is / was? I miss curve ;-)

**Comment by scd** [comment]
We will be doing CPR curves for gyms. This is a regression issue.

https://www.thecrag.com/climber/anderlnought

How much did you look at your gym progress? What where you looking for?

Outdoors we have sport/trad/bouldering. But what groupings shall we use for indoors.

We would also like to talk to some gyms.

**Comment by birgander2** [comment]
No worries, I think I can live without for the moment ;-) I was using it for sport only. Bouldering is important, too, but my gym doesn't grade boulders, so it is quite useless for me to log something. I was mainly looking at the "performance" curve (but only from time to time) and also on the number of ascents. 

I think to do it the same way as for outdoors, but only for sport/bouldering would be fine as a starting point. I think the possibility for a ranking only based on ascents in a particular gym would be a nice feature, too. I suppose this is already there in the climber tab (but a bit hidden).

**Comment by Mdemaillard** [comment]
I believe all points are closed on this issue. A few dedicated points are logged separately.
closing.
