### ISSUE TITLE
Staring at the sea has 8 stars 

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#3870]
**What happened?**
A route has suddenly acquired more stars, and more than the usual range, 

It doesn't look like it is due to an edit, but rather a bug

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/australia/blue-mountains/centennial-glen/route/145344540

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/22091505/111021238-0fde1f80-841f-11eb-8963-cb7c2c0fbbec.png)

**What you expected:**
It to have a star number between 0-5

**Comment by DaneEvans** [comment]
Has now dropped back to 0.  I don't know what it was originally, but it has a couple in a few of the grade contributions.  

I don't know if you guys changed anything to fix it, or whether it's an issue that needs watching

**Comment by rouletout** [comment]
We had something similar in issue https://github.com/theCrag/website/issues/2866 which also resolved all by itself. Keep an eye on it for now.

**Comment by rouletout** [comment]
Fixed itself, closing

**Comment by DaneEvans** [comment]
You say as you open the potentially similar #3886

Just making sure the cross-linking is there if we have a deeper star
display problem

**Comment by rouletout** [comment]
This seems to happen over and over again, here from social:

**Comment by scd** [comment]
Please post links as it saves searching:

https://www.thecrag.com/en/climbing/australia/blue-mountains/porters-pass/route/13152373

**Comment by scd** [comment]
So I have done some triage and an internal statistic NumberQualityRatings is negative which should not be possible.

```
                            'NQR' => -3,
```

I have refactored the algorithm so it will not use QualityRatings if the NumberQualityRatings is negative. This will fix the problem of having stars greater than three, but does not fix the statistics data integrity issue. It is most probably that this issue comes from statistics been updated incrementally, in particular some process that effectively changes a user quality rating. This will be difficult and time consuming to track down and involves code review and testing of every process in the system that effects user rating and possibly even looking for processes that accidentally effect user ratings.

Doing a statistics baseline recalculation for the route fixes the instance of bad statistics data integrity.

**Comment by rouletout** [comment]
Closing this in favour of https://github.com/theCrag/website/issues/3940 which seems the more general issue.
